// Two lists, deliberately. `allowed` decides whether a guess is a real word
// and is permissive, so normal words are never rejected. `answers` is the
// only source of secret words and is curated down to words people actually
// know. Both are generated by scripts/build_wordlists.py.
import allowedRaw from "./allowed.json";
import answersRaw from "./answers.json";

export const WORD_LENGTH = 5;
export const MAX_ATTEMPTS = 6;

const SCORES = { 0: 20, 1: 15, 2: 10, 3: 7, 4: 5, 5: 2 };

// Strips accents but keeps \u00f1 as its own letter: \u00f1 decomposes to n + combining
// tilde, so a naive diacritic strip silently turns PE\u00d1A into PENA and makes
// the \u00d1 key on the keyboard do nothing.
export const normalizeWord = (word) => {
  if (!word) return "";
  return word
    .toLowerCase()
    .normalize("NFD")
    // every combining accent except the tilde
    .replace(/[\u0300-\u0302\u0304-\u036f]/g, "")
    // ...and the tilde too, unless it is sitting on an n, which makes it a ñ
    .replace(/(?<!n)\u0303/g, "")
    .normalize("NFC")
    .toUpperCase();
};

const answers = answersRaw.map(normalizeWord);
const allowedSet = new Set(allowedRaw.map(normalizeWord));

export const calculateScore = (attemptIndex) => SCORES[attemptIndex] ?? 0;

export const isValidWord = (word) => allowedSet.has(normalizeWord(word));

export const checkGuess = (guess, target) => {
  const guessArr = normalizeWord(guess).split("");
  const targetArr = normalizeWord(target).split("");
  const result = new Array(WORD_LENGTH).fill("absent");
  const targetCounts = {};

  targetArr.forEach((c) => {
    targetCounts[c] = (targetCounts[c] || 0) + 1;
  });
  guessArr.forEach((c, i) => {
    if (c === targetArr[i]) {
      result[i] = "correct";
      targetCounts[c]--;
    }
  });
  guessArr.forEach((c, i) => {
    if (result[i] !== "correct" && targetCounts[c] > 0) {
      result[i] = "present";
      targetCounts[c]--;
    }
  });
  return result;
};

export const getDailyKey = (date = new Date()) => date.toISOString().split("T")[0];

const getISOWeekKey = (date) => {
  const d = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));
  const weekNo = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);
  return `${d.getUTCFullYear()}-W${weekNo}`;
};

export const getRoundKey = (frequency, date = new Date()) => {
  if (frequency === "weekly") return getISOWeekKey(date);
  if (frequency === "quarterly") {
    return `${date.getUTCFullYear()}-Q${Math.floor(date.getUTCMonth() / 3) + 1}`;
  }
  return getDailyKey(date);
};

// Start/end instants (UTC) of the round containing `date`.
export const getRoundBoundaries = (date, frequency) => {
  const d = new Date(date);
  d.setUTCHours(0, 0, 0, 0);

  if (frequency === "daily") {
    const start = new Date(d);
    const end = new Date(d);
    end.setUTCDate(end.getUTCDate() + 1);
    end.setUTCMilliseconds(-1);
    return { start, end };
  }
  if (frequency === "weekly") {
    const day = d.getUTCDay();
    const diff = d.getUTCDate() - day + (day === 0 ? -6 : 1);
    const start = new Date(d);
    start.setUTCDate(diff);
    start.setUTCHours(0, 0, 0, 0);
    const end = new Date(start);
    end.setUTCDate(start.getUTCDate() + 7);
    end.setUTCMilliseconds(-1);
    return { start, end };
  }
  if (frequency === "quarterly") {
    const quarter = Math.floor(d.getUTCMonth() / 3);
    const start = new Date(Date.UTC(d.getUTCFullYear(), quarter * 3, 1));
    const end = new Date(Date.UTC(start.getUTCFullYear(), start.getUTCMonth() + 3, 1));
    end.setUTCMilliseconds(-1);
    return { start, end };
  }
  return null;
};

function hashString(str) {
  let hash = 0;
  for (let i = 0; i < str.length; i++) {
    hash = (hash << 5) - hash + str.charCodeAt(i);
    hash |= 0;
  }
  return Math.abs(hash);
}

// Deterministic PRNG, so a league's word order is fixed forever and
// reproducible from its id alone — nothing about the schedule is stored.
function mulberry32(seed) {
  return function next() {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

// Each league walks its own shuffled permutation of the answer list, so it
// uses every word once before any repeat. Picking by `hash(day) % length`
// instead — as this used to — silently skips some words and repeats others,
// which is invisible with thousands of words but obvious with ~1,200.
const orderCache = new Map();

function wordOrderFor(leagueId) {
  let order = orderCache.get(leagueId);
  if (order) return order;

  const rng = mulberry32(hashString(leagueId));
  order = answers.slice();
  for (let i = order.length - 1; i > 0; i--) {
    const j = Math.floor(rng() * (i + 1));
    [order[i], order[j]] = [order[j], order[i]];
  }
  orderCache.set(leagueId, order);
  return order;
}

const EPOCH_UTC = Date.UTC(2026, 0, 1);

// The one function that decides the secret word. Runs only in this Worker —
// the word lists it reads are never bundled into the website.
export function getTargetWord(leagueId, dailyKey) {
  const order = wordOrderFor(leagueId);
  const day = Math.floor((Date.parse(`${dailyKey}T00:00:00Z`) - EPOCH_UTC) / 86400000);
  return order[((day % order.length) + order.length) % order.length];
}
